### ISSUE TITLE
How to build gerbera for FreeBSD?

### ISSUE THREAD

**Issue by ieg999** [v00d00/gerbera#100]
Hi!

How to build gerbera for FreeBSD 11?
I can't find any instructions like for other systems...

Best regards, Ivan.

**Comment by v00d00** [comment]
Hi! No one has created/linked me to a FreeBSD ports package yet.

You could try building from source, the "Quick start build instructions" should work for you:

```
git clone https://github.com/v00d00/gerbera.git
mkdir build
cd build
cmake ../gerbera -DWITH_MAGIC=1 -DWITH_MYSQL=1 -DWITH_CURL=1 -DWITH_JS=1 \
-DWITH_TAGLIB=1 -DWITH_AVCODEC=1 -DWITH_EXIF=1 -DWITH_LASTFM=1
make -j4
sudo make install
```

Please let me know how you get on!

**Comment by ieg999** [comment]
Hi!

I have some troubles. Gerbera requires libupnp 1.8.0 or above, but the last version of libupnp is 1.6.22.
Maybe I'm doing something wrong?

root@freebsd:/home/ivan/gerbera # git clone https://github.com/v00d00/gerbera.git
Клонирование в «gerbera»…
remote: Counting objects: 23458, done.
remote: Compressing objects: 100% (80/80), done.
remote: Total 23458 (delta 66), reused 94 (delta 46), pack-reused 23332
Получение объектов: 100% (23458/23458), 8.72 MiB | 466.00 KiB/s, готово.
Определение изменений: 100% (16526/16526), готово.
root@freebsd:/home/ivan/gerbera # mkdir build
root@freebsd:/home/ivan/gerbera # cd build
root@freebsd:/home/ivan/gerbera/build # cmake ../gerbera -DWITH_MAGIC=1 -DWITH_MYSQL=1 -DWITH_CURL=1 -DWITH_JS=1 -DWITH_TAGLIB=1 -DWITH_AVCODEC=1 -DWITH_EXIF=1 -DWITH_LASTFM=1
-- The C compiler identification is Clang 3.8.0
-- The CXX compiler identification is Clang 3.8.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/CC
-- Check for working CXX compiler: /usr/bin/CC -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST - Failed
-- Found Iconv: /usr/local/lib/libiconv.so
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "1.3.7") 
-- Checking for one of the modules 'uuid'
-- Could NOT find UPnP (missing:  UPNP_UPNP_LIBRARY UPNP_INCLUDE_DIR) 
CMake Error at CMakeLists.txt:354 (message):
  gerbera requires libupnp 1.8.0 or above.


-- Configuring incomplete, errors occurred!
See also "/home/ivan/gerbera/build/CMakeFiles/CMakeOutput.log".
See also "/home/ivan/gerbera/build/CMakeFiles/CMakeError.log".
root@freebsd:/home/ivan/gerbera/build # 

Best regards, Ivan

**Comment by v00d00** [comment]
You do need 1.8

You can get it from upstream: https://github.com/mrjimenez/pupnp/releases/tag/release-1.8.1

**Comment by ieg999** [comment]
Hi !
I have build pupnp libraries. 
Now i need mysql to be installed. Can i get the full list of dependencies?

root@freebsd:/home/ivan/gerbera # cd build
root@freebsd:/home/ivan/gerbera/build # cmake ../gerbera -DWITH_MAGIC=1 -DWITH_MYSQL=1 -DWITH_CURL=1 -DWITH_JS=1 -DWITH_TAGLIB=1 -DWITH_AVCODEC=1 -DWITH_EXIF=1 -DWITH_LASTFM=1
-- The C compiler identification is Clang 3.8.0
-- The CXX compiler identification is Clang 3.8.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/CC
-- Check for working CXX compiler: /usr/bin/CC -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST - Failed
-- Found Iconv: /usr/local/lib/libiconv.so
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "1.3.7") 
-- Checking for one of the modules 'uuid'
-- Found UPnP: /usr/local/lib/libupnp-1.8.so (found version "1.8.1") 
CMake Warning at CMakeLists.txt:360 (message):
  

   !! It is strongly recommended to build libupnp with --enable-reuseaddr !!

  Without this option Gerbera will be unable to restart with the same port
  number.


-- Found EXPAT: /usr/local/lib/libexpat.so (found version "2.2.0") 
-- Checking for module 'sqlite3'
--   Found sqlite3, version 3.17.0
-- Found Sqlite3: /usr/local/lib/libsqlite3.so
-- Looking for nl_langinfo
-- Looking for nl_langinfo - found
-- Looking for setlocale
-- Looking for setlocale - found
-- Found INOTIFY: /usr/local/include  
-- Could NOT find Duktape (missing:  DUKTAPE_LIBARY DUKTAPE_INCLUDE_DIR) 
CMake Error at cmake/FindMySQL.cmake:112 (MESSAGE):
  Cannot find MySQL.  Include dir: MYSQL_INCLUDE_DIR-NOTFOUND library dir:
Call Stack (most recent call first):
  CMakeLists.txt:421 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/ivan/gerbera/build/CMakeFiles/CMakeOutput.log".
See also "/home/ivan/gerbera/build/CMakeFiles/CMakeError.log".

**Comment by ieg999** [comment]
MySQL is working!
And now we have:

root@freebsd:/home/ivan/gerbera/build # cmake ../gerbera -DWITH_MAGIC=1 -DWITH_MYSQL=1 -DWITH_CURL=1 -DWITH_JS=1 -DWITH_TAGLIB=1 -DWITH_AVCODEC=1 -DWITH_EXIF=1 -DWITH_LASTFM=1
-- The C compiler identification is Clang 3.8.0
-- The CXX compiler identification is Clang 3.8.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/CC
-- Check for working CXX compiler: /usr/bin/CC -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST - Failed
-- Found Iconv: /usr/local/lib/libiconv.so
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "1.3.7") 
-- Checking for one of the modules 'uuid'
-- Found UPnP: /usr/local/lib/libupnp-1.8.so (found version "1.8.1") 
CMake Warning at CMakeLists.txt:360 (message):
  

   !! It is strongly recommended to build libupnp with --enable-reuseaddr !!

  Without this option Gerbera will be unable to restart with the same port
  number.


-- Found EXPAT: /usr/local/lib/libexpat.so (found version "2.2.0") 
-- Checking for module 'sqlite3'
--   Found sqlite3, version 3.17.0
-- Found Sqlite3: /usr/local/lib/libsqlite3.so
-- Looking for nl_langinfo
-- Looking for nl_langinfo - found
-- Looking for setlocale
-- Looking for setlocale - found
-- Found INOTIFY: /usr/local/include  
-- Could NOT find Duktape (missing:  DUKTAPE_LIBARY DUKTAPE_INCLUDE_DIR) 
-- MySQL Include dir: /usr/local/include/mysql  library dir: /usr/local/lib/mysql
-- MySQL client libraries: /usr/local/lib/mysql/libmysqlclient_r.so
-- Found CURL: /usr/local/lib/libcurl.so (found version "7.54.0") 
CMake Error at cmake/FindTaglib.cmake:56 (include):
  include could not find load file:

    FindLibraryWithDebug
Call Stack (most recent call first):
  CMakeLists.txt:446 (find_package)


CMake Error at cmake/FindTaglib.cmake:68 (find_library_with_debug):
  Unknown CMake command "find_library_with_debug".
Call Stack (most recent call first):
  CMakeLists.txt:446 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/ivan/gerbera/build/CMakeFiles/CMakeOutput.log".
See also "/home/ivan/gerbera/build/CMakeFiles/CMakeError.log".

**Comment by v00d00** [comment]
You need taglib, version 1.11.1.

There is a script for that one also.

**Comment by ieg999** [comment]
Good evening!
I have built taglib libraries successfully.
But now we have problems with Duktape. 
"pkg install duktape" doesn't work.. 
What version do i need? and how integrate duktape.c, duktape.h, and duk_config.h to your build?

root@freebsd:/home/ivan/gerbera/build # cmake ../gerbera -DWITH_MAGIC=1 -DWITH_MYSQL=1 -DWITH_CURL=1 -DWITH_JS=1 -DWITH_TAGLIB=1 -DWITH_AVCODEC=1 -DWITH_EXIF=1 -DWITH_LASTFM=1
-- The C compiler identification is Clang 3.8.0
-- The CXX compiler identification is Clang 3.8.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/CC
-- Check for working CXX compiler: /usr/bin/CC -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST - Failed
-- Found Iconv: /usr/local/lib/libiconv.so
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "1.3.7") 
-- Checking for one of the modules 'uuid'
-- Found UPnP: /usr/local/lib/libupnp-1.8.so (found version "1.8.1") 
CMake Warning at CMakeLists.txt:360 (message):
  

   !! It is strongly recommended to build libupnp with --enable-reuseaddr !!

  Without this option Gerbera will be unable to restart with the same port
  number.


-- Found EXPAT: /usr/local/lib/libexpat.so (found version "2.2.0") 
-- Checking for module 'sqlite3'
--   Found sqlite3, version 3.17.0
-- Found Sqlite3: /usr/local/lib/libsqlite3.so
-- Looking for nl_langinfo
-- Looking for nl_langinfo - found
-- Looking for setlocale
-- Looking for setlocale - found
-- Found INOTIFY: /usr/local/include  
-- Could NOT find Duktape (missing:  DUKTAPE_LIBARY) 
CMake Error at CMakeLists.txt:418 (message):
  Duktape not found!


-- Configuring incomplete, errors occurred!
See also "/home/ivan/gerbera/build/CMakeFiles/CMakeOutput.log".
See also "/home/ivan/gerbera/build/CMakeFiles/CMakeError.log".

**Comment by v00d00** [comment]
You need duktape built as a shared library. or `WITH_JS=0`

**Comment by ieg999** [comment]
Ok.
"cmake ../gerbera -DWITH_MAGIC=1 -DWITH_MYSQL=1 -DWITH_CURL=1 -DWITH_JS=1 -DWITH_TAGLIB=1 -DWITH_AVCODEC=1 -DWITH_EXIF=1 -DWITH_LASTFM=0" completed successfully.  
But there is a problem with the linker:

[ 94%] Building CXX object CMakeFiles/libgerbera.dir/src/youtube_video_url.cc.o
[ 95%] Building CXX object CMakeFiles/libgerbera.dir/src/zmm/array.cc.o
[ 95%] Building CXX object CMakeFiles/libgerbera.dir/src/zmm/exception.cc.o
[ 96%] Building CXX object CMakeFiles/libgerbera.dir/src/zmm/stringtokenizer.cc.o
[ 97%] Building CXX object CMakeFiles/libgerbera.dir/src/zmm/object.cc.o
[ 98%] Building CXX object CMakeFiles/libgerbera.dir/src/zmm/stringbuffer.cc.o
[ 99%] Building CXX object CMakeFiles/libgerbera.dir/src/zmm/strings.cc.o
[ 99%] Built target libgerbera
Scanning dependencies of target gerbera
[ 99%] Building CXX object CMakeFiles/gerbera.dir/src/main.cc.o
[100%] Linking CXX executable gerbera
CMakeFiles/libgerbera.dir/src/mt_inotify.cc.o: In function `Inotify::Inotify()':
/home/ivan/gerbera/gerbera/src/mt_inotify.cc:(.text+0x35): undefined reference to `inotify_init'
CMakeFiles/libgerbera.dir/src/mt_inotify.cc.o: In function `Inotify::supported()':
/home/ivan/gerbera/gerbera/src/mt_inotify.cc:(.text+0x2d9): undefined reference to `inotify_init'
CMakeFiles/libgerbera.dir/src/mt_inotify.cc.o: In function `Inotify::addWatch(zmm::String, int)':
/home/ivan/gerbera/gerbera/src/mt_inotify.cc:(.text+0x342): undefined reference to `inotify_add_watch'
CMakeFiles/libgerbera.dir/src/mt_inotify.cc.o: In function `Inotify::removeWatch(int)':
/home/ivan/gerbera/gerbera/src/mt_inotify.cc:(.text+0x56a): undefined reference to `inotify_rm_watch'
c++: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1

Stop.
make[2]: stopped in /usr/home/ivan/gerbera/build
*** Error code 1

Stop.
make[1]: stopped in /usr/home/ivan/gerbera/build
*** Error code 1

Stop.
make: stopped in /usr/home/ivan/gerbera/build
root@freebsd:/home/ivan/gerbera/build #

**Comment by v00d00** [comment]
Hmm, it ntshould I be using inotify on non Linux. I'll have a look in the morning!

Thanks for your patience! We are treading a new path here

**Comment by ieg999** [comment]
Ok. Thanks for your answers..

**Comment by v00d00** [comment]
Odd, Inotify should only be enabled

**Comment by v00d00** [comment]
CMake must have found an INotify header on your system some how?!

`sys/inotify.h` is the file it looks for?

**Comment by v00d00** [comment]
So apparently there is an inotify shim [libinotify-kqueue](https://github.com/libinotify-kqueue/libinotify-kqueue) based on kqueue which installs the header. Quite cool!

I will add support for that package later today, should be pretty simple.

**Comment by v00d00** [comment]
@ieg999 Please try it and let me know 👍

**Comment by v00d00** [comment]
Closing on the assumption all is good. Please reopen if not.

**Comment by ieg999** [comment]
It works!... Thank you!

**Comment by ieg999** [comment]
...but when i run gerbera, i get this error: :((

[ivan@freebsd ~]$ /usr/local/bin/gerbera
2017-06-16 20:53:43    INFO: Gerbera UPnP Server version 1.1.0_alpha - http://gerbera.io/
2017-06-16 20:53:43    INFO: ===============================================================================
2017-06-16 20:53:43    INFO: Gerbera is free software, covered by the GNU General Public License version 2
2017-06-16 20:53:43    INFO: Copyright 2016-2017 Gerbera Contributors.
2017-06-16 20:53:43    INFO: Gerbera is based on MediaTomb: Copyright 2005-2010 Gena Batsyan, Sergey Bostandzhyan, Leonhard Wimmer.
2017-06-16 20:53:43    INFO: Loading configuration from: /home/ivan/.config/gerbera/config.xml
2017-06-16 20:53:43    INFO: Checking configuration...
2017-06-16 20:53:43    INFO: Setting filesystem import charset to UTF-8
2017-06-16 20:53:43    INFO: Setting metadata import charset to UTF-8
2017-06-16 20:53:43    INFO: Setting playlist charset to UTF-8
2017-06-16 20:53:43 WARNING: You enabled the YouTube feature, which allows you
                             to watch YouTube videos on your UPnP device!
                             Please check http://www.youtube.com/t/terms
                             By using this feature you may be violating YouTube
                             service terms and conditions!

2017-06-16 20:53:43    INFO: Configuration check succeeded.
2017-06-16 20:53:43 WARNING: IP is null
Exception raised in [src/server.cc:135] upnp_init(): upnp_init: UpnpInit failed
2017-06-16 20:53:43   ERROR: main: upnp error -205
2017-06-16 20:53:43   ERROR: upnp_cleanup: UpnpUnRegisterRootDevice failed
Exception raised in [src/server.cc:260] shutdown(): upnp_cleanup: UpnpUnRegisterRootDevice failed
[ivan@freebsd ~]$

**Comment by v00d00** [comment]
Oh no!

That is an error from libupnp that means it cant create a socket. I have no experience on FreeBSD, is there something specific that needs doing?
```
/*!
 * \brief The SDK cannot create any more sockets.
 *
 * This occurs in any function that makes network connections, such as discovery
 * (e.g. \b UpnpSearchAsync or \b UpnpSendAdvertisement), control (e.g.
 * \b UpnpSendAction), eventing (e.g. \b UpnpNotify), and HTTP functions (e.g. 
 * \b UpnpDownloadXmlDoc).
 */
#define UPNP_E_OUTOF_SOCKET		-205
```

**Comment by v00d00** [comment]
Do you have other media servers running perhaps? or other things using UPNP? or maybe its some FreeBSD security issue?

There are some from MediaTomb here: https://sourceforge.net/p/mediatomb/discussion/440751/thread/98233e8a/

**Comment by ieg999** [comment]
No, i havent other media servers running. I can try to get and run MediaTomb from FreeBSD ports, but i can do this after my vacation... in two weeks time.

**Comment by v00d00** [comment]
Can you see if there is any other app using port 1900?

**Comment by gerroon** [comment]
Is there a way to change the default port 1900?

**Comment by elmodaddyb** [comment]
@gerroon  - The Universal Plug-n-Play specification uses port = 1900 @ UDP to broadcast availability to UPnP media clients(TVs, game consoles, etc).  If the port changes on the running server, it may also have to change on the clients listening.

You might be able to manage some type of `port-translation` using a router, if you wanted to send traffic on a different port.  However, I think at some point that traffic will have to go over port 1900 so that listening clients will see the available gerbera server....and the media it can server.

**Comment by gerroon** [comment]
@elmodaddyb 
thanks for the explanation. The reason I asked was that I have bunch of dlna servers running on my system (do not ask why) , I just wanted to make sure that the conflict would not cause any issue in the network.
