### ISSUE TITLE
Ubuntu PPA not working for 16.04 server

### ISSUE THREAD

**Issue by uncaught** [v00d00/gerbera#101]
Hello, the [Ubuntu PPA](https://launchpad.net/~stephenczetty/+archive/ubuntu/mediatomb-v00d00) is not working on Ubuntu 16.04:

> W: The repository 'http://ppa.launchpad.net/stephenczetty/mediatomb-v00d00/ubuntu xenial Release' does not have a Release file.
 
Could you please fix it? 

---

The installation instruction for a manual build are quite complicated with those extra dependencies (taglib and libupnp). First there are missing unlisted dependencies in the instructions:
+ cmake
+ build-essentials (for CXX compiler)
+ autoreconf (for the install-pupnp18.sh)

And then I finally ran into this with install-pupnp18.sh:

> pupnp-release-1.8.1/upnp/unittest/templates/templates.h
> + cd pupnp-release-1.8.1
> + ./bootstrap
> configure.ac:550: error: possibly undefined macro: AC_PROG_LIBTOOL
>       If this token and others are legitimate, please use m4_pattern_allow.
>       See the Autoconf documentation.
> autoreconf: /usr/bin/autoconf failed with exit status: 1

Here I had to stop, this is too much for a simple end-user installation :(

Thank you for your work! :)

**Comment by Shadow4711** [comment]
Hello,

perhaps you need to install libtool.

**Comment by v00d00** [comment]
He does need libtool.

@stephenczetty looks after that PPA so hopefully he can comment.

**Comment by uncaught** [comment]
Okay with libtool the libupnp install worked, but then the cmake ran into the next problem:

CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:52 (find_package_handle_standard_args)
  cmake/FindLastFMLib.cmake:3 (find_package)
  CMakeLists.txt:494 (find_package)

**Comment by Shadow4711** [comment]
pkg-config is missing.

**Comment by uncaught** [comment]
Thanks, but now the next lib is missing. Maybe you could try your insrructions with a blank new ubuntu and complete it?

I think I will just wait for the PPA update or a full insrallation instruction with all dependencies.

**Comment by stephen-czetty** [comment]
I never did a build for xenial before now, it took a little bit of tweaking of dependencies to get it to work.

Note that I have created a new ppa that reflects the rename of the project: http://ppa.launchpad.net/stephenczetty/gerbera/ubuntu

There are packages for gerbera 1.0.0 for xenial, yakkety, and zesty (16.04, 16.10, and 17.04)

**Comment by v00d00** [comment]
@uncaught Is this sorted for you now?

**Comment by v00d00** [comment]
Going to assume its all good. Please reopen if not 👍
