### ISSUE TITLE
gerbera crashing when starting playback

### ISSUE THREAD

**Issue by imbezol** [v00d00/gerbera#103]
Using upnp from kodi client on Android. Can list media on kodi but there is no file info like filesizes or previews. When clicking on a video to start playback the gerbera server crashes.

[trace.txt](https://github.com/v00d00/gerbera/files/1106900/trace.txt)

**Comment by imbezol** [comment]
[config.xml.txt](https://github.com/v00d00/gerbera/files/1106904/config.xml.txt)

**Comment by v00d00** [comment]
@stephen-czetty could this be a packaging issue?

**Comment by v00d00** [comment]
I can replicate this.

Can you confirm you have `<mark-played-items enabled="yes"`?

**Comment by imbezol** [comment]
Yup.

> grep played config.xml 
      <mark-played-items enabled="yes" suppress-cds-updates="yes">
      </mark-played-items>

**Comment by imbezol** [comment]
If I turn that option off gerbera does not crash.

**Comment by v00d00** [comment]
You can also fix it by adding:

```
<mark>
  <content>audio</content>
  <content>video</content>
  <content>image</content>
</mark>
```
Into the mark-played-items tag.

I will look into adding some validation so that at least one content must be set.

**Comment by imbezol** [comment]
Thanks.. confirmed it works with those. They should likely be added to the default config in the package.
