### ISSUE TITLE
lastfmlib

### ISSUE THREAD

**Issue by marceloneil** [v00d00/gerbera#107]
It took me a bit to figure out that I needed the 2009 [lastfmlib](https://code.google.com/archive/p/lastfmlib/) rather than the more recent [liblastfm](https://github.com/lastfm/liblastfm). Would it make sense to create an `install-lastfm.sh` script similar to the other dependency install scripts, or is there something that I'm missing here. If an installer script would be useful, I've already made one and would be happy to make a PR

**Comment by v00d00** [comment]
If you would like to contribute your script, please do!

I think the newer lib needs Qt, so cant use that.
