### ISSUE TITLE
Mac OSX fails

### ISSUE THREAD

**Issue by Tibbs** [v00d00/gerbera#109]
Hi,

I've been trying to build Gerbera on macOS but it fails. Please help with this.
I disabled most optional libraries, but something wrong with iconv

I use this cmake command:
cmake ../gerbera -DWITH_MAGIC=0 -DWITH_MYSQL=0 -DWITH_CURL=0 -DWITH_JS=0 -DWITH_TAGLIB=0 -DWITH_AVCODEC=0 -DWITH_FFMPEGTHUMBNAILER=0 -DWITH_EXIF=0 -DWITH_LASTFM=0

"make -j4" output:
[  1%] Building CXX object CMakeFiles/libgerbera.dir/src/atrailers_service.cc.o
[  3%] Building CXX object CMakeFiles/libgerbera.dir/src/action_request.cc.o
[  3%] Building CXX object CMakeFiles/libgerbera.dir/src/atrailers_content_handler.cc.o
[  3%] Building CXX object CMakeFiles/libgerbera.dir/src/autoscan.cc.o
[  4%] Building CXX object CMakeFiles/libgerbera.dir/src/autoscan_inotify.cc.o
[  5%] Building CXX object CMakeFiles/libgerbera.dir/src/buffered_io_handler.cc.o
[  6%] Building CXX object CMakeFiles/libgerbera.dir/src/cached_url.cc.o
[  6%] Building CXX object CMakeFiles/libgerbera.dir/src/cds_objects.cc.o
[  7%] Building CXX object CMakeFiles/libgerbera.dir/src/cds_resource.cc.o
[  8%] Building CXX object CMakeFiles/libgerbera.dir/src/cds_resource_manager.cc.o
[  9%] Building CXX object CMakeFiles/libgerbera.dir/src/config_manager.cc.o
[ 10%] Building CXX object CMakeFiles/libgerbera.dir/src/content_manager.cc.o
[ 10%] Building CXX object CMakeFiles/libgerbera.dir/src/curl_io_handler.cc.o
[ 11%] Building CXX object CMakeFiles/libgerbera.dir/src/destroyer.cc.o
[ 12%] Building CXX object CMakeFiles/libgerbera.dir/src/dictionary.cc.o
[ 13%] Building CXX object CMakeFiles/libgerbera.dir/src/exceptions.cc.o
[ 14%] Building CXX object CMakeFiles/libgerbera.dir/src/fd_io_handler.cc.o
[ 14%] Building CXX object CMakeFiles/libgerbera.dir/src/file_io_handler.cc.o
[ 15%] Building CXX object CMakeFiles/libgerbera.dir/src/file_request_handler.cc.o
[ 16%] Building CXX object CMakeFiles/libgerbera.dir/src/filesystem.cc.o
[ 18%] Building CXX object CMakeFiles/libgerbera.dir/src/io_handler_buffer_helper.cc.o
[ 18%] Building CXX object CMakeFiles/libgerbera.dir/src/generic_task.cc.o
[ 18%] Building CXX object CMakeFiles/libgerbera.dir/src/io_handler.cc.o
[ 19%] Building CXX object CMakeFiles/libgerbera.dir/src/io_handler_chainer.cc.o
[ 20%] Building CXX object CMakeFiles/libgerbera.dir/src/jpeg_resolution.cc.o
[ 21%] Building CXX object CMakeFiles/libgerbera.dir/src/lastfm_scrobbler.cc.o
[ 22%] Building CXX object CMakeFiles/libgerbera.dir/src/layout/fallback_layout.cc.o
[ 22%] Building CXX object CMakeFiles/libgerbera.dir/src/layout/js_layout.cc.o
[ 23%] Building CXX object CMakeFiles/libgerbera.dir/src/logger.cc.o
[ 24%] Building C object CMakeFiles/libgerbera.dir/src/md5/md5.c.o
[ 25%] Building CXX object CMakeFiles/libgerbera.dir/src/mem_io_handler.cc.o
[ 25%] Building CXX object CMakeFiles/libgerbera.dir/src/memory.cc.o
[ 26%] Building CXX object CMakeFiles/libgerbera.dir/src/metadata/exiv2_handler.cc.o
[ 27%] Building CXX object CMakeFiles/libgerbera.dir/src/metadata/ffmpeg_handler.cc.o
[ 28%] Building CXX object CMakeFiles/libgerbera.dir/src/metadata_handler.cc.o
[ 29%] Building CXX object CMakeFiles/libgerbera.dir/src/metadata/libexif_handler.cc.o
[ 29%] Building CXX object CMakeFiles/libgerbera.dir/src/metadata/taglib_handler.cc.o
[ 30%] Building CXX object CMakeFiles/libgerbera.dir/src/metadata/fanart_handler.cc.o
[ 31%] Building CXX object CMakeFiles/libgerbera.dir/src/mt_inotify.cc.o
[ 32%] Building CXX object CMakeFiles/libgerbera.dir/src/mxml/attribute.cc.o
[ 33%] Building CXX object CMakeFiles/libgerbera.dir/src/mxml/comment.cc.o
[ 33%] Building CXX object CMakeFiles/libgerbera.dir/src/mxml/context.cc.o
[ 34%] Building CXX object CMakeFiles/libgerbera.dir/src/mxml/document.cc.o
[ 35%] Building CXX object CMakeFiles/libgerbera.dir/src/mxml/element.cc.o
[ 36%] Building CXX object CMakeFiles/libgerbera.dir/src/mxml/node.cc.o
[ 37%] Building CXX object CMakeFiles/libgerbera.dir/src/mxml/parseexception.cc.o
[ 37%] Building CXX object CMakeFiles/libgerbera.dir/src/mxml/parser_expat.cc.o
[ 38%] Building CXX object CMakeFiles/libgerbera.dir/src/mxml/xml_text.cc.o
[ 39%] Building CXX object CMakeFiles/libgerbera.dir/src/mxml/xml_to_json.cc.o
[ 40%] Building CXX object CMakeFiles/libgerbera.dir/src/online_service.cc.o
[ 41%] Building CXX object CMakeFiles/libgerbera.dir/src/online_service_helper.cc.o
[ 41%] Building CXX object CMakeFiles/libgerbera.dir/src/play_hook.cc.o
[ 42%] Building CXX object CMakeFiles/libgerbera.dir/src/process.cc.o
[ 43%] Building CXX object CMakeFiles/libgerbera.dir/src/process_executor.cc.o
[ 44%] Building CXX object CMakeFiles/libgerbera.dir/src/process_io_handler.cc.o
[ 45%] Building CXX object CMakeFiles/libgerbera.dir/src/request_handler.cc.o
[ 45%] Building CXX object CMakeFiles/libgerbera.dir/src/rexp.cc.o
[ 46%] Building CXX object CMakeFiles/libgerbera.dir/src/scripting/import_script.cc.o
[ 47%] Building CXX object CMakeFiles/libgerbera.dir/src/scripting/js_functions.cc.o
[ 48%] Building CXX object CMakeFiles/libgerbera.dir/src/scripting/playlist_parser_script.cc.o
[ 49%] Building CXX object CMakeFiles/libgerbera.dir/src/scripting/runtime.cc.o
[ 49%] Building CXX object CMakeFiles/libgerbera.dir/src/scripting/script.cc.o
[ 50%] Building CXX object CMakeFiles/libgerbera.dir/src/server.cc.o
[ 51%] Building CXX object CMakeFiles/libgerbera.dir/src/serve_request_handler.cc.o
[ 52%] Building CXX object CMakeFiles/libgerbera.dir/src/session_manager.cc.o
[ 52%] Building CXX object CMakeFiles/libgerbera.dir/src/singleton.cc.o
[ 53%] Building CXX object CMakeFiles/libgerbera.dir/src/sopcast_content_handler.cc.o
[ 54%] Building CXX object CMakeFiles/libgerbera.dir/src/sopcast_service.cc.o
[ 55%] Building CXX object CMakeFiles/libgerbera.dir/src/storage/cache_object.cc.o
[ 56%] Building CXX object CMakeFiles/libgerbera.dir/src/storage.cc.o
[ 56%] Building CXX object CMakeFiles/libgerbera.dir/src/storage/mysql/mysql_storage.cc.o
[ 57%] Building CXX object CMakeFiles/libgerbera.dir/src/storage/sqlite3/sqlite3_storage.cc.o
[ 58%] Building CXX object CMakeFiles/libgerbera.dir/src/storage/sql_storage.cc.o
[ 59%] Building CXX object CMakeFiles/libgerbera.dir/src/storage/storage_cache.cc.o
[ 60%] Building CXX object CMakeFiles/libgerbera.dir/src/string_converter.cc.o
[ 60%] Building CXX object CMakeFiles/libgerbera.dir/src/subscription_request.cc.o
/Users/macos/Documents/iOS/Mirror/gerbera/gerbera/src/string_converter.cc:133:11: error: no matching function for call to 'libiconv'
    ret = iconv(cd, (char**)input_ptr, &input_bytes,
          ^~~~~
/Library/Frameworks/libiconv.framework/Headers/iconv.h:87:15: note: expanded from macro 'iconv'
#define iconv libiconv
              ^~~~~~~~
/Library/Frameworks/libiconv.framework/Headers/iconv.h:89:37: note: candidate function not viable: no known conversion from 'char **' to 'const char **' for
      2nd argument
extern LIBICONV_DLL_EXPORTED size_t iconv (iconv_t cd, const char* * inbuf, size_t *inbytesleft, char* * outbuf, size_t *outbytesleft);
                                    ^
/Library/Frameworks/libiconv.framework/Headers/iconv.h:87:15: note: expanded from macro 'iconv'
#define iconv libiconv
              ^
1 error generated.
make[2]: *** [CMakeFiles/libgerbera.dir/src/string_converter.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/libgerbera.dir/all] Error 2
make: *** [all] Error 2

**Comment by v00d00** [comment]
Thanks for reporting, which version of iconv do you have?

**Comment by Tibbs** [comment]
I used brew to install and it is version 1.15

**Comment by v00d00** [comment]
Our findiconv cmake file already checks the signedness, and the code already has ifdef, but the two communicate that information.

**Comment by Tibbs** [comment]
@v00d00 Sorry I'm not sure what you meant. Do you have any suggestion hoe to resolve this?

**Comment by v00d00** [comment]
Can you try with latest master? https://github.com/v00d00/gerbera/commit/e0c8e2d5240c1f2d02931c0307b305da5199c1cc

**Comment by v00d00** [comment]
@Tibbs I'm going to close this on the assumption that commit fixed it. Please let reopen if not.
