### ISSUE TITLE
Able to source from a local pulseaudio stream

### ISSUE THREAD

**Issue by bjbeare** [v00d00/gerbera#110]
Can I set gerbera to take a source from pulseaudio? Perhaps via a plugin?

Media clients would then  connect via DLNA/UPNP and request the stream.

**Comment by v00d00** [comment]
Its an interesting idea, but a bit out of scope at the moment. We are focusing on local media for now.

You could run https://github.com/masmu/pulseaudio-dlna, on the same machine though!
