### ISSUE TITLE
Status icon distorted in Web UI

### ISSUE THREAD

**Issue by michael-o** [v00d00/gerbera#116]
From master:

    [~/Projekte/gerbera/web/icons]$ file status*
    status_loading.png:         PNG image data, 25 x 38, 8-bit/color RGBA, non-interlaced
    status_updates_pending.png: PNG image data, 25 x 38, 8-bit/color RGBA, non-interlaced
    status.png:                 PNG image data, 38 x 38, 8-bit/color RGBA, non-interlaced

As you can see, `status.png` is the Gerbera flower with 38x38, but

    [~/Projekte/gerbera/web]$ grep -r status.png .
    ./top.html:                            <span id="statusNoUpdates"><img src="icons/status.png" width="25" height="38" alt="idle" class="status"></span>
    ./top.html:                            <img src="icons/status.png" width="25" height="38" border="0" alt="idle" class="status" id="statusIdle">

it is distorted down to 25 pixels in widths assuming that this is still the MediaTomb skull.

**Comment by v00d00** [comment]
I had noticed this one too, but not got around to actually changing it.

I was planning on adding a new in progress icon.
