### ISSUE TITLE
Enhanced Metadata for image/jpeg

### ISSUE THREAD

**Issue by r-clips** [v00d00/gerbera#121]
Would really appreciate ability to access Xmp tags for image files.

I have been using mediatomb for several years to serve up a photo collection with a virtual directory structure organised by keyword tags applied by photo oganisers like ‘Shotwell’, ‘Digikam’ etc 
These Tags are not available through libexif and are typically stored as Xmp or IPTC tags ( specifically Xmp.dc.Subject ).

With Mediatomb, I hacked together this functionality through libextractor, but I see that libextractor has gone from Gerbera.  The alternative is to use exiv2 directly to access Xmp metadata - Exiv2 still seems to be present in Gerbera code, but is currently disabled.

I have put together a set of patches that :
      -  re-enable exiv2 library interface in gerbera
      -  add code to exiv2_handler to support ‘auxdata’  library-option to access either Exif or Xmp tags

My coding skills ( particularly in C++ ) are fairly rudimentary, but the attached patches work for me. Make use of anything that might be useful.

[gerbera-exiv2-patches.zip](https://github.com/v00d00/gerbera/files/1172476/gerbera-exiv2-patches.zip)

Also, I note that it looks like exiv2 supports matroska mkv containers, so this could go some way towards addressing Issue #30 

Incidentally, really appreciative that Mediatomb has been resurrected and polished up for 2017

**Comment by v00d00** [comment]
Hi,

Thanks for this, it looks great. Can you open a pull request for these?

**Comment by v00d00** [comment]
Which email/name do you want me to use when committing these?

**Comment by r-clips** [comment]
OK, just reading some git-hub howto's ....
As soon as I get to the bit that explains pull-requests, I'll give it a shot .....

>> Which email/name do you want me to use when committing these?
 
  I assumed this would be the git-hub user name.

**Comment by v00d00** [comment]
To clarify, I asked for you email/username as I could have taken the patches from the zip and commited them on your behalf if you would have preffered. It looks like you got the PR sorted though, so no need.

Thanks for the contribution!

We need to put some documentation together really.
