### ISSUE TITLE
Unable to install.  - Upnp-1.8.so issue.

### ISSUE THREAD

**Issue by LinuxUser2017** [v00d00/gerbera#124]
Hello,

I'm using a raspberry pi 3, 
Linux securitypi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux.

I have used the ./scripts folder to fix dependency issues (particularly for upnp 1.8.0). 

I get this error : 

[ 99%] Built target libgerbera
Scanning dependencies of target gerbera
make[2]: *** No rule to make target '/usr/lib/arm-linux-gnueabihf/libupnp-1.8.so', needed by 'gerbera'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 99%] Building CXX object CMakeFiles/gerbera.dir/src/main.cc.o
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/gerbera.dir/all' failed
make[1]: *** [CMakeFiles/gerbera.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

after make -j4

So I figure that's related to lib UPNP 1.8.0. The /scripts/install-pupnp18.sh  completes properly.

It turns out libupnp-1.8.so wasn't in /usr/lib/arm-linux-gnuabihf folder. Also, you can't tell libupnp to install to a location that doesn't end in /usr/lib. : 
libtool: install: error: cannot install `libupnp-1.8.la' to a directory not ending in /usr/lib

I had to create symlinks from /usr/lib to /usr/lib/arm-linux-gnuabihf folder to get make -j4 complete. 

...now I get a web interface.

**Comment by v00d00** [comment]
This sounds more like a libupnp bug, perhaps raise it [with upstream?](https://github.com/mrjimenez/pupnp)
