### ISSUE TITLE
Some command line options don't work.

### ISSUE THREAD

**Issue by LinuxUser2017** [v00d00/gerbera#125]
Hello,

gerbera --compile-info just starts the server as per normal.
gerbera --version also does the same
gerbera -d doesn't run the server in the background.

Raspberry Pi3 - 
Linux  4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux

**Comment by v00d00** [comment]
1. Restore compile info #43 is still on my ToDo
2. 🐛 
3. `-d` was removed intentionally (use your init system to run it instead).

**Comment by v00d00** [comment]
Thanks for reporting 👍
