### ISSUE TITLE
Reintroduce user and group support

### ISSUE THREAD

**Issue by michael-o** [v00d00/gerbera#127]
In commit 2a5dfac70f8d81bbb8b293a19189b19b5cd2ce7f this feature was dropped with reasoning "Your init system can set the user/group for you". While most systems will support UID/GID change, this causes further problems: 

1. pid file cannot be created in /var/run/gerbera.pid anymore
2. log file cannot be created in /var/log/gerbera.log anymore

Any reason not to keep it even if start systems can perfom a `su(1)` command? One would need to require to wrap this with  [`daemon(8)`](https://www.freebsd.org/cgi/man.cgi?query=daemon&sourceid=opensearch) or similar.

**Comment by v00d00** [comment]
I think we just need to introduce a `gerbera` folder into those paths at install time, and then drop the files down a level.

e.g. at install create `/var/run/gerbera` and `/var/log/gerbera` with the correct ownership, then update the default paths.

**Comment by michael-o** [comment]
Well, I have thought of that, but creating a directory for just one file like `gerbera.log`/`gerbera.pid` sounds awkward to me. I think that it will mean any harm to keep this feature for those who want to use it.

**Comment by v00d00** [comment]
I still think that the init system is the best place to control this.

Here is a link to the [Gentoo OpenRC](https://gitweb.gentoo.org/repo/gentoo.git/tree/net-misc/gerbera/files/gerbera-1.0.0.initd) script, for reference.

**Comment by michael-o** [comment]
It pretty much looks like the RC script on FreeBSD. I will resort to `daemon(8)` then.
