### ISSUE TITLE
EXIF data

### ISSUE THREAD

**Issue by LinuxUser2017** [v00d00/gerbera#134]
Hello,

Just a couple queries about the EXIF support in gerbera. 
I have compiled with EXIF=1 but I don't see any EXIF-specific information on my device. (Only sorts photos by Date or Directories or year). 

So I have two questions : 
- What extra functionality does EXIF=1 enable currently ?
- Is it possible to enable complete (search able) EXIF metadata functionality (ISO / shutter speed / Categories / Tags list)?

**Comment by v00d00** [comment]
It allows you to use EXIF fields in your custom scripted layout, so you can have folders based on those values for instance.

Search is not implemented, and it wouldnt be able to search with those values as they arent part of the Upnp spec. Unless you had those values in the item name perhaps (which is scriptable).
