### ISSUE TITLE
trying to compile in debian

### ISSUE THREAD

**Issue by tommyp-vr4** [v00d00/gerbera#135]
Dumb question - Is it possible to alter things to use debian's version of duktape for Gerbera?  Reason I ask is that I like to install programs via deb installers.  I've already done this for libupnp-1.8.  Seems as it is now, the only way to compile is to make the duktape in the scripts folder.

**Comment by v00d00** [comment]
Debian ship a duktape binary, not library, so we cannot link to it.

Sorry!

Maybe ask them for a libduktape? Perhaps @jcowgill can comment.

**Comment by jcowgill** [comment]
No, Debian ships all the duktape source in the `duktape-dev` package.

**Comment by v00d00** [comment]
There is the dev package, but there is also https://packages.debian.org/sid/amd64/duktape/filelist
