### ISSUE TITLE
nothing here works

### ISSUE THREAD

**Issue by m6969p** [v00d00/gerbera#139]
clean destruction of mediatomb!
ppa gives 404
no ubuntu biuild working (maybe on hte author's weird own private config, but not on a clean release with the prerequisites added as requested).

cmake what is you need?    learn how to make a package first before creating something with your personal levels of sw installed on whatever weird system you created.

this project is in the pre-pre release state called "total junk, waste of time"

junk!

**Comment by v00d00** [comment]
Hi Mike,

I don't actually maintain the PPA, but just checking it seems to be there, perhaps you could give us some info which file was not found for you?

Could you provide the version of Ubuntu and the commands you ran and some logs for the build, I'm sure we can sort out the issue you were having with the build.

Thanks!

**Comment by m6969p** [comment]
closing things when received is not the right answer to an issue.
Looks you are new at developing anything:

sure, we 'can sort it out ', that's not the goal of a 'release'.

Mark it as unmaintained and under development. Then just run it out of the git rep from a new box where you have not added all the nice things you use personally, like the latest greatest cmake and insisting on it, and thus disabling the entire thing to run on a 'real production system'.

You will see yourself that the entire setup is not working the way you start released it.

minidlna, survey says "MINIDLNA is the dlna package that runs out of the box and gets the donation.

**Comment by asavah** [comment]
@m6969p Your rant does not provide any useful information to troubleshoot the issues you are having.
Just sayin'
