### ISSUE TITLE
In some cases, inotify can lead to crashes

### ISSUE THREAD

**Issue by gburca** [v00d00/gerbera#38]
When I enable inotify on a particular directory, mediatomb crashes. Will add more details to this issue once I've narrowed down what's causing the crash.

**Comment by v00d00** [comment]
Can you try 96c644943f000cdc1646a13a2ae0d6f7a82cb323?

**Comment by v00d00** [comment]
I haven't seen any inotify crashes for some time, so going to close this.

Please reopen if you spot more.
