### ISSUE TITLE
Restore compile info

### ISSUE THREAD

**Issue by v00d00** [v00d00/gerbera#43]
And include git rev hash.

**Comment by elmodaddyb** [comment]
Can you help clarify??

Is `COMPILE_INFO` the compilation options passed to CMAKE? Or something more?

```
-DWITH_MAGIC=1 -DWITH_MYSQL=1 -DWITH_CURL=1 -DWITH_TAGLIB=1 -DWITH_AVCODEC=1 -DWITH_EXIF=1 -DWITH_LASTFM=1
```

**Comment by v00d00** [comment]
Yeah, so the idea is that we pass a summary of the options that were passed to CMake as a definition, then at runtime return that info.

Its useful for people to see if they have for example ffmpeg or taglib enabled in the build for example.

We should also put the git revision if built from git.

**Comment by elmodaddyb** [comment]
OK, makes sense.  It should be easy enough to create a new class `BuildInformation` and include the GIT HASH and CMAKE options.

**Comment by elmodaddyb** [comment]
@v00d00  - I got the compile info all set.  Working on the Git revision hash.  Should have a PR soon.

**Comment by cweiske** [comment]
`gerbera --compile-info` shows the compilation options.
