### ISSUE TITLE
Update JS Engine/Nuke Spidermonkey

### ISSUE THREAD

**Issue by v00d00** [v00d00/gerbera#47]
Our spidermonkey code is very old, as is the version of spidermonkey it needs.

Its also way over the top for our scripting needs.

Lets switch to something smaller and designed to be embedded such as [Duktape](http://duktape.org/) or [MuJS](http://mujs.com/docs/reference).

**Comment by sdrik** [comment]
Did you already start working on this ? If not, I'd like to volunteer.

**Comment by v00d00** [comment]
Hey, I havent started working on it yet. I look forward to seeing what you come up with.

**Comment by gburca** [comment]
Are the two proposed replacements strict supersets of Spidermonkey as far as gerbera is concerned? If not, some of the scripts that used to work might break when swapping the JS engine. Debugging JS is tedious for this type of embedded environment. At least with spidermonkey or node.js there's no question of what JS language features are supported.

**Comment by v00d00** [comment]
In the case of `duktape`, which I am leaning towards, it implements ECMAScript 5.1, with SpiderMonkey (1.8.5) we are on ECMAScript 5.0. It also has nice things like [Encoder API](https://encoding.spec.whatwg.org/) and some more modern ES6/7 features. We _should_ only gain more support from using it.

**Comment by v00d00** [comment]
It also has a [provided debugger](https://github.com/svaarala/duktape/blob/master/doc/debugger.rst).

**Comment by gburca** [comment]
That sounds good.

**Comment by v00d00** [comment]
This was done with #64. Thanks to @sdrik
