### ISSUE TITLE
Rebrand

### ISSUE THREAD

**Issue by v00d00** [v00d00/gerbera#54]
So having spoken to the original authors of MediaTomb they would rather keep the name mediatomb associated with them, which is fair enough.

So we need a new name for the project going forward....

**Comment by tommyp-vr4** [comment]
Some ideas to throw out there. 
UDMA (ultimate digital media archive; nice geeky play on letters)
dlnArchive (play on words with dlna but doesn't roll off the tongue)
hypermedia
mediarevelation (because mediatomb was brought back from the dead)
mediacache or mediadepot

**Comment by v00d00** [comment]
I was thinking a bit more abstract probably an animal or a plant or something like that.

**Comment by gburca** [comment]
I'd vote for something unique. Searching for UDMA is bound to return everything except this project. Bonus points if the domain name is not yet taken.

Unfortunately obvious names like MediaVault are already in use. FaSoLa seems more unique than DoReMi, but the domain names are taken.

Are the original authors OK with copying the static web site content to the new project?

**Comment by v00d00** [comment]
Ive gone with "Gerbera" after a[ family of pretty flowers](https://en.wikipedia.org/wiki/Gerbera).

Here is my badly inkscaped attempt at logo:

<Img src="https://github.com/v00d00/gerbera/blob/master/artwork/logo-horiz.png?raw=true" width="50%"/>

And I have registered a fasionable `io` domain: `gerbera.io`, we are modern now! 😆 

@gburca I've mailed the original authors about the content on mediatomb.cc, its not obvious what licence the sites content is under it just says "copyright", so we shall see what they come back with.

**Comment by v00d00** [comment]
If anyone knows a friendly web developer who wants to make us a website, please send them my way.

**Comment by elmodaddyb** [comment]
Hello, Great to see Gerbera on GitHub.  I am playing around with the front-end of MediaTomb (frameset 👎 )... moving to a modern client application using Angular with ES6, Bootstrap 4.

Wondering if there is any appetite for a modern client side for Gerbera?  Or is branding, solely to remove the references to MediaTomb?

Any insights....thoughts...direction?

Thanks,
E

**Comment by v00d00** [comment]
@elmodaddyb: There is absolutely an appitite for a modern UI, its high on the wish list.

In terms to technologies ideally for simplicity I would like a SPA that has no compilation requirement, BS4 is ideal, and uses jquery so perhaps that would be enough in terms of libraries for this case.

**Comment by elmodaddyb** [comment]
@v00d00 - Great suggestions.  ES6 compliation is a pain & complex (as I am finding...)  When I make some progress I will shout....its a weekend/night project, so may take some time.  Will keep you posted.

**Comment by v00d00** [comment]
Closing this as it pretty much complete.

Ive opened #84 to track the progress on an updated Web UI.
