### ISSUE TITLE
import.js and/or common.js problem

### ISSUE THREAD

**Issue by tommyp-vr4** [v00d00/gerbera#60]
I finally tried gerbera on a real machine.  Is anyone having a problem importing videos & pictures using the default import.js / common.js scripting?  My gerbera/config.xml has the virtual-layout type="js". My gerbera log file says:

JS: /usr/share/gerbera/js/import.js:154: ReferenceError: object_root_path is not defined

I tried using some print commands in import.js and it appears that the object_root_path is indeed empty (obj.location is fine). Just wondering if either I did something odd when I compiled or if something isn't working right.  I can run some debug cases - just let me know what to do so I can get the data needed to help.

**Comment by v00d00** [comment]
This is interesting as `object_root_path` isn't mentioned anywhere else in the code?!

**Comment by v00d00** [comment]
Ah ha! Its in https://github.com/v00d00/gerbera/commit/7f86d4a460ddc08e0bc293d46e315f11c6456ae4

**Comment by tommyp-vr4** [comment]
I'm not too sure this can be closed yet.  I recompiled and I still get the object_root_path is not defined error.  :(
