### ISSUE TITLE
Does playlist ordering work?

### ISSUE THREAD

**Issue by GrahamCobb** [v00d00/gerbera#61]
If you would prefer that we do not use Issues to ask questions, feel free to delete this.

I have been trying to get mediatomb working and have hit a problem, so I am wondering if this also occurs in gerbera (it isn't mentioned on the list of differences).

I have a large (500 tracks) playlist, which is in a specific order. All the clients I have tried with mediatomb (and the mediatomb web interface itself) show the list in alphabetical order, even though the playlist.js is setting the item.playlistOrder correctly. I can't be certain whether this is mediatomb's problem, or the clients are re-sorting.

Does anyone use playlists with specific ordering in gerbera and do they work? If they do, I will make the effort to build this on debian testing and give it a go.

**Comment by v00d00** [comment]
Hi Graham,

That is not something I have tested, so I would assume it would be the same as MediaTomb. Somebody may have some more experience with playlists, such as @gburca.

I would encourage you to try it and report back, possibly with a test case, if you are wiling to!

**Comment by gburca** [comment]
For me, it depends on the DLNA renderer I use. My receiver retained the same order as the m3u file. The Roku insisted on sorting the playlist alphabetically.

In my `playlists.js` I now append the playlistOrder to the title to make everyone happy. Ex:

```
var playlistOrder = 1;

function addPlaylistItem(location, title, playlistChain, order) {
    // ...
    item.playlistOrder = (order ? order : playlistOrder++);
    item.title = pad(item.playlistOrder, 3) + " " + item.title;
    // ...
}
```

**Comment by GrahamCobb** [comment]
Thanks @gburca. That is what I am doing today (and will probably continue to do for my very long playlists as too many clients also forget where they are in the playlist if you pause them for a while, so it is helpful for moving to the right place to continue). But I would quite like to avoid having to do it for short playlists (especially as many tracks already have lots of information encoded into the title, like composer, movement numbers, etc).

I will give gerbera a try at some point and see if I can find some clients which keep the playlist ordering. I might then even see if I could make nested playlists work.
