### ISSUE TITLE
Make it easier to install on Ubuntu

### ISSUE THREAD

**Issue by dandv** [v00d00/gerbera#63]
I've [added the PPA](https://github.com/v00d00/gerbera#ubuntu), but it's unclear what to do next. `apt install gerbera` didn't work. `apt install mediatomb` seems to install the old fork. After that, launching MediaTomb from the shortcut that gets installed, navigates me to `file:///var/lib/mediatomb/mediatomb.html`, which is missing. Launching `mediatomb` from a terminal seems to launch the old project.

**Comment by v00d00** [comment]
I guess we just need to ask @stephen-czetty to update the PPA...

**Comment by stephen-czetty** [comment]
Apologies, I just had a baby so this isn't on the top of my list of things to get done....  I'll take a shot at it soon, hopefully later this week.

**Comment by v00d00** [comment]
Thanks, and congratulations!

**Comment by stephen-czetty** [comment]
Updated the ppa, please give it a shot.  I didn't try to migrate the old database on upgrade, I can work on fixing that, but my own database had gotten so messed up that it wasn't a huge priority for me. :)

**Comment by v00d00** [comment]
Thanks Stephen!
