### ISSUE TITLE
"FFMpeg/LibAV not found" when omitting "-DWITH_AVCODEC=1"

### ISSUE THREAD

**Issue by cweiske** [v00d00/gerbera#67]
I removed `-DWITH_AVCODEC=1` from the cmake command and still got an error:

> CMake Error at CMakeLists.txt:494 (message):
>  FFMpeg/LibAV not found

I had to pass the parameter with value 0 to overcome this. If it's really optional, it should default to 0 in my eyes.

**Comment by v00d00** [comment]
It's optional, I think some things should be enabled by default though, but as you discovered you can just turn it off anyway.
