### ISSUE TITLE
Restarting gerbera: New port used

### ISSUE THREAD

**Issue by cweiske** [v00d00/gerbera#71]
My `config.xml` file specifies that server port 49152 shall be used. When restarting gerbera, it switches to port 49153. When restarting again, it goes to 49152 again. When waiting some time until starting gerbera after stopping it, the port is not switched to 49153.

This was already a problem with mediatomb. Maybe you could fix this for gerbera.

**Comment by v00d00** [comment]
This is the default annoying behaviour of libupnp. If you are running master try building pupnp with the --enable-reuseaddr flag.

https://github.com/mrjimenez/pupnp/pull/23
