### ISSUE TITLE
assertion failed when adding text file via web interface

### ISSUE THREAD

**Issue by cweiske** [v00d00/gerbera#73]
I have some scripts that push data into mediatomb/gerbera via the web interface AJAX API, using my PHP library [Services_MediaTomb](https://github.com/cweiske/Services_MediaTomb). After switching to Gerbera, they fail and gerbera crashes because an assertion fails.

The following URLs are called:

```
http://dojo:49152/content/interface?req_type=auth&action=get_sid&sid=null
http://dojo:49152/content/interface?req_type=auth&action=get_token&sid=866cc65df0f5ef9876cdbac783bcb828
http://dojo:49152/content/interface?sid=866cc65df0f5ef9876cdbac783bcb828&req_type=auth&action=login&username=cweiske&password=b37098fdcdedca1257c81248bcdc9d1f
http://dojo:49152/content/interface?sid=866cc65df0f5ef9876cdbac783bcb828&req_type=containers&parent_id=0&select_it=0
http://dojo:49152/content/interface?sid=866cc65df0f5ef9876cdbac783bcb828&req_type=containers&parent_id=39338&select_it=0
http://dojo:49152/content/interface?sid=866cc65df0f5ef9876cdbac783bcb828&req_type=add_object&parent_id=39339&title=item+%230&location=%2Ftmp%2Fmediatombtest%2Ffile.txt&class=object.item&obj_type=item&description=Just+a+test&mime-type=text%2Fplain
```

After the last URL call, gerbera crashes:

> Apr 16 21:30:25 dojo gerbera[29527]: gerbera: /usr/local/src/gerbera/src/storage/sql_storage.cc:225: zmm::Ref<CdsObject> SQLStorage::checkRefID(zmm::Ref<CdsObject>): Zusicherung »0« nicht erfüllt.

It's german but the message says "Assertion »0« not fulfilled".

The text file that gets added actually exists and has a couple of bytes content.

**Comment by v00d00** [comment]
So if you look at the assert[1] there is a comment that it should never happen...

We always enable the asserts now though, so it is crashing. Perhaps it is no longer a valid assertion?

1. https://github.com/v00d00/gerbera/blob/master/src/storage/sql_storage.cc#L223
