### ISSUE TITLE
Listing artists and albums is slow

### ISSUE THREAD

**Issue by cweiske** [v00d00/gerbera#75]
Since the introduction of folder images (which I absolutely love!), opening folders with many subfolders is too slow. It takes around 10 seconds to get the list of artists here (about 130). This is too long.

**Comment by v00d00** [comment]
I've just tested this with my collection and speed seems fine, though I am using sqlite.

Could you try with sqlite and see if you have the same issue? That way we know to focus on mysql or not.

**Comment by v00d00** [comment]
Do you mean in the Web UI?

**Comment by cweiske** [comment]
No, not the web UI. I mean listing albums and artists is slow with a UPnP client.

I'll have a look at it later this week. The next few days I'll be away.

**Comment by cweiske** [comment]
I enabled MySQL's general query log and got a log of all quries.

Now I see that fetching the cover image for a single album takes 200ms:

```
RESET QUERY CACHE;
SELECT `id`
FROM `mt_cds_object`
WHERE
 (
  lower(`dc_title`) LIKE 'cover.jp%'
  OR lower(`dc_title`) LIKE 'albumart%.jp%'
  OR lower(`dc_title`) LIKE 'album.jp%'
  OR lower(`dc_title`) LIKE 'front.jp%'
  OR lower(`dc_title`) LIKE 'folder.jp%'
 )
 AND `upnp_class`='object.item.imageItem'
 AND `parent_id` IN (
  SELECT `parent_id`
  FROM `mt_cds_object`
  WHERE
   `parent_id`='14343'
   AND `object_type`=2
 )
ORDER BY `dc_title` DESC
```

Doing that for the 261 albums I have takes time.

**Comment by cweiske** [comment]
I wonder why that subquery is needed. It returns the `parent_id` for items with the `parent_id = 14343`.

When removing that subquery and replacing it with `AND parent_id='14343'` I'm down to 2ms for the query.

**Comment by v00d00** [comment]
Hmm yeah, that doesnt make too much sense at first glance!

Are you happy having a stab at putting together a patch for this?

**Comment by cweiske** [comment]
I digged a bit deeper.

The original patch https://sourceforge.net/p/mediatomb/discussion/440751/thread/6578cd15/#f4a5 did two subselects.
It was made for virtual folders and items, fetched the folder IDs of the *real/original files* - and looked there for images.

The current code only looks for files that are directly in the (virtual) folder.

**Comment by cweiske** [comment]
@whorfin - why did you remove the 2nd subselect from the cover art patch (fa8a1976ff)? Currently virtual folders do not get any cover art automatically. The original patch provided this feature.

**Comment by whorfin** [comment]
I was not able to test it in my configuration at the time.
My motivation for the patch was extending the name categories [case folding, generalizing extension, increasing candidate names to match minidlna] and adding track art support.

The omission was in the spirit of "don't break what you can't test", not "I think that behavior is a bad idea" - when I added the two selects as present in that original patch, I experienced SQLLite errors so I backed off.  Lots was different in that build so it might ultimately have been unrelated; there were
locking bugs.
I agree I should have trimmed the subselect.

Feel free to add the other behavior if you need/want it.
