### ISSUE TITLE
Create default config in ~/.config/

### ISSUE THREAD

**Issue by cweiske** [v00d00/gerbera#76]
The [freedesktop folder specification](https://specifications.freedesktop.org/basedir-spec/latest/) says that configuration files should be put into `~/.config/` (or `$XDG_CONFIG_HOME` if it is set).

Gerbera creates the config.xml file in `~/.gerbera/config.xml`, which clutters the home directory with another folder.

I suggest `~/.config/gerbera.xml` as default location.

**Comment by v00d00** [comment]
Agreed, should be a nice easy patch for someone also.

I do like having the sqlite and config near eachother though. I think we can class the sqlite as config for this rather than putting it in DATA_DIR

**Comment by cweiske** [comment]
The SQLlite database is data by definition and should be in DATA_DIR by default. You may configure it otherwise yourself. Gerbera will be running on servers mostly where home directories are irrelevant anyway (/etc/gerbera being used there).
