### ISSUE TITLE
Album Artist

### ISSUE THREAD

**Issue by v00d00** [v00d00/gerbera#79]
We need it, especially for `dc:creator`, which is currently set to the first tracks artist. Which can sometimes look odd, especially on compilations.

**Comment by sdrik** [comment]
In already have something like that in my fork, but I feed it in `<upnp:artist role="AlbumArtist">`.
Take a look at 0f280a22d42f2242caaa5a83c1b77e356b360032.

**Comment by v00d00** [comment]
@sdrik sorry, just seen your message, I have grabbed ff36f9cb91cdffa455a684e7e5d7e0c036266128 and ff36f9cb91cdffa455a684e7e5d7e0c036266128 from your fork.
