### ISSUE TITLE
MySQL server has gone away

### ISSUE THREAD

**Issue by cweiske** [v00d00/gerbera#82]
The second time in a week I had the following error in my logs:

> Mai 05 18:31:34 dojo gerbera[15713]: Exception raised in [src/storage/mysql/mysql_storage.cc:365] exec(): Mysql: mysql_real_query() failed: mysql_error (2006): "MySQL server has gone away"; query: UPDATE `mt_autoscan` SET `last_modified`=1486286336 WHERE `id`=1

Maybe a timeout. Gerbera should reconnect then.

**Comment by v00d00** [comment]
Yeah agreed, I will take a look this weekend.

**Comment by cweiske** [comment]
Works fine!

**Comment by v00d00** [comment]
Thanks for testing!
