### ISSUE TITLE
armhf build?

### ISSUE THREAD

**Issue by SandPox** [v00d00/gerbera#85]
Hello, I've just came across this project and found out it's quite useful so I'm planning to use it on my Raspberry Pi which is running ARM arch, the compiling process of this require a lot of unnecessary dependency that needs to be installed so I think it's a good idea to add arm* to ppa builds.

**Comment by elmodaddyb** [comment]
@SandPox - that would be a cool idea.  I have an intel edison arduino that maybe could test out a build on that...  I am wondering if you have found a list of the `unnecessary` dependencies.  Do you think we could eliminate capability to remove the dependencies somehow?

Let me know what you think?

**Comment by SandPox** [comment]
eh, I haven't success to compile it on my RPI so...

by the "unnecessary dependencies" I mean an end user like me have no requirement to compile from source code which will need a lots of *-dev packages. If this get compiled to .deb with taglib and libupnp for ARM arch then I could install and run it right away without care about -dev build dependencies.

**Comment by elmodaddyb** [comment]
I see what you mean.  The **-dev** packages does take time to collect and install.  As you mentioned a binary install for ARM platform would make it very extensible to IOT devices...which is common for media center setups.

**Comment by v00d00** [comment]
This is a question for @stephen-czetty

**Comment by stephen-czetty** [comment]
I enabled arm builds in the PPA, but I haven't tested them at all.  Good news is that they built without any changes, so they are probably good.

Please give it a shot, let me know if anything needs to be adjusted in the package.

**Comment by elmodaddyb** [comment]
If I get some time later in the week, I'll see if I can fire up the Intel Edison board I have and drop Ubuntu + Gerbera.

Any ideal **distro** version to test for the setup?

**Comment by v00d00** [comment]
@elmodaddyb I would go with ubuntu as the PPA provides the arm version.

**Comment by v00d00** [comment]
Closing this as ARM builds fine. Please report issues separately.
