### ISSUE TITLE
SessionManager checkTimer deadlock?

### ISSUE THREAD

**Issue by elmodaddyb** [v00d00/gerbera#86]
Hello All,

I am running a recent local build of Gerbera on my local and hitting a deadlock consistently when the `SessionManager.checkTimer()` clears the stale sessions.

> Here is the scenario.

1. Open Gerbera web UI @ `http://localhost:49152`
2. Establish a session (with SID and logged in)
3. Wait for `SessionManager::timerNotify` to fire, and cleanup the stale sessions

It looks like the `Timer` mutex is `AutoLock` 2 times. First on the `Timer::notify`, to call the SessionManager cleanup, then again on the `Timer::removeTimerSubscriber`

```
void  Timer::notify()
{
    AutoLock lock(mutex);
```
Sessions are removed via `SessionManager::timerNotify` and the `SessionManager::checkTimer` is called to clear the Timer.

```
void Timer::removeTimerSubscriber(Subscriber* timerSubscriber, zmm::Ref<Parameter> parameter, bool dontFail)
{
    log_debug("Removing subscriber...\n");

    AutoLock lock(mutex);

   ^^^^^ DEADLOCK ^^^^^
```

The deadlock consistently happens on the second call to the `AutoLock lock(mutex)` for the `Timer` instance.

My guess is that I have missed some simple configuration or runtime difference, but cannot figure it out.  Likely due to inexperience with C++.

Any helpful direction would be appreciated.  If anyone else sees similar issue and has ideas it would be great!.

Thanks,

Eamonn

**Comment by elmodaddyb** [comment]
Well, tried a few things...still hitting deadlock.  I found that older MediaTomb @ d6028b64c9f36ec35b0287137d2b50210754fabd removes the `SessionManager` timer immediately upon creating it (never triggering cleanup) 👎 . Then there is no chance that the timer will deadlock, later.  It seems the `SessionManager` timer gets immediately erased after creation via a `notify()`:

https://github.com/v00d00/gerbera/blob/master/src/timer.cc#L143

... which is triggered by `main.cc` timer call which has since been removed 

https://github.com/v00d00/gerbera/blob/master/src/main.cc#L410

Down the rabbit hole...We'll see where it goes!!

**Comment by elmodaddyb** [comment]
System is using :
`class Timer : public Singleton<Timer, std::mutex> {`
looks like this causes deadlocks when the `AutoLock lock(mutex)` is called multiple times by the same thread, which is the case with the `SessionManager::timerNotify`

I changed to a recursive mutex, which frees up the thread to call `AutoLock lock(mutex)` multiple times.
`class Timer : public Singleton<Timer, std::recursive_mutex> {`

However, then all terribleness occurs with **Signal: SIGSEGV (Segmentation fault)** due to erasing the subscribers while iterating over `std::list<TimerSubscriberElement> subscribers;`

**Comment by v00d00** [comment]
Nice, investigation, if your analysis is correct, then removing the `AutoLock` in `SessionManager::timerNotify` should fix this (no need to lock as we already have the lock), can you test this for me?

**Comment by elmodaddyb** [comment]
@v00d00 - I will test it out and submit a pull request for the same.  May be ready to pull mid-week!

**Comment by elmodaddyb** [comment]
**Success!!!**
I think I found a feasible solution.

1. Change `Timer` class to use `recursive_mutex`, this allows for multiple `AutoLock lock(mutex)` on the same thread, same `Timer` mutex. MT was running this way a while back.
```
class Timer : public Singleton<Timer, std::recursive_mutex>
```

2. Modify the `Timer::notify` to use an intermediary `std::list`
     - First, collect all subscribers that must be notified, into `std::list<TimerSubscriberElement> toNotify;`
     - Second, iterate over `toNotify` and trigger the `element.notify()`

This allows the `subscribers` iterator to remain unchanged, when looping through `notify` and avoids the **SIGSEGV** due to changing list.

I'll post a pull request soon as I figure out a reasonable way to test it [GoogleTest??](https://github.com/google/googletest)

**Comment by gburca** [comment]
@elmodaddyb perhaps instead of making the mutex recursive, you can rearrange the notify() code to:

1. lock
2. iterate through the subscribers and
    1. populate `toNotify`
    2. remove the `isOnce()` ones (see below)
3. unlock
4. iterate `toNotify` and call `element.notify()`

Even though `element.notify()` may end up calling `removeTimerSubscriber()` or `addTimerSubscriber()`, the subscribers list is not locked and can be modified.

For removing elements from a `std::list` while iterating over it:
```
for (auto it = list.begin(); it != list.end(); ) {
  if (it->isOnce()) {
    it = list.erase(it);
  } else {
    ++it;
  }
}
```

With this change, perhaps `TimerSubscriberElement::disabled` can also be eliminated.

**Comment by elmodaddyb** [comment]
@gbruca, Thanks for taking time to explain.  I greatly appreciate the information.

I will try as you mentioned an report back!

**Comment by elmodaddyb** [comment]
That seems to have done the trick.  Able to eliminate **disabled** and keep **mutex**

I will test a bit more this time with live runtime 🥇  to avoid any obvious bugs.

**Comment by v00d00** [comment]
@elmodaddyb are you happy to push your code?

**Comment by elmodaddyb** [comment]
@v00d00 - With help from @gburca , it looks like the latest changes are feasible.  I am working to retest a bit more then will submit the PR.

Thanks, 
Eamonn
