### ISSUE TITLE
ffmpeg_handler.cc - warnings about sprintf format specifier : should be %lld not just %ld

### ISSUE THREAD

**Issue by Corin-EU** [v00d00/gerbera#89]
Gerbera builds cleanly apart from one set of warnings.

     [ 27%] Building CXX object CMakeFiles/libgerbera.dir/src/metadata/ffmpeg_handler.cc.o
     /srv/repository/git/gerbera/src/metadata/ffmpeg_handler.cc: In function 'void      addFfmpegResourceFields(zmm::Ref<CdsItem>, AVFormatContext*, int*, int*)':
     /srv/repository/git/gerbera/src/metadata/ffmpeg_handler.cc:154:97: warning: format '%ld' expects argument of type 'long int', but argument 3 has type 'int64_t {aka long long int ' [-Wformat=]
         sprintf(duration, "%02ld:%02ld:%02ld.%01ld", hours, mins, secs, (10 * us) / AV_TIME_BASE);
                                                                                                 ^
     /srv/repository/git/gerbera/src/metadata/ffmpeg_handler.cc:154:97: warning: format '%ld' expects argument of type 'long int', but argument 4 has type 'int64_t {aka long long int ' [-Wformat=]
     /srv/repository/git/gerbera/src/metadata/ffmpeg_handler.cc:154:97: warning: format '%ld' expects argument of type 'long int', but argument 5 has type 'int64_t {aka long long int ' [-Wformat=]
     /srv/repository/git/gerbera/src/metadata/ffmpeg_handler.cc:154:97: warning: format '%ld' expects argument of type 'long int', but argument 6 has type 'int64_t {aka long long int ' [-Wformat=]

So the format specifiers on line 154 of ffmpeg_handler.cc should be of type %lld not just %ld.

      sprintf(duration, "%02lld:%02lld:%02lld.%01lld", hours, mins, secs, (10 * us) / AV_TIME_BASE);

[ffmpeg_handler.cc_patch.txt](https://github.com/v00d00/gerbera/files/1027132/ffmpeg_handler.cc_patch.txt)

**Comment by v00d00** [comment]
You can send me a pull request or a git format patch and then I can apply it (and you get due credit in the history), or I can just apply the above?

**Comment by v00d00** [comment]
Also, out of interest which compiler and ffmpeg do you have?

**Comment by Corin-EU** [comment]
The versions I did the build with are

      gcc (Debian 4.9.2-10) 4.9.2  

      ffmpeg version 3.2.4 Copyright (c) 2000-2017 the FFmpeg developers
      built with gcc 4.9.2 (Debian 4.9.2-10)

Please just use the code submitted above as appropriate but as you are getting a warning with the change it loooks like some ifdef (?) / preprocessor type testing needs to be done to check wthere int64_t is long or long long int.

Probably it is because I have done this compilation on a 32 bit system so it is long long, whereas for you on a 64 bit system it is  just long.

After a quick web search -- maybe the PRId64 macro is the easiest way to ensure portability.

More information at <https://stackoverflow.com/questions/9225567/how-to-print-a-int64-t-type-in-c>

**Comment by v00d00** [comment]
Thanks!
