### ISSUE TITLE
How do you enable ffmpegthumbnailer?

### ISSUE THREAD

**Issue by asavah** [v00d00/gerbera#94]
It seems that enabling building with ffmpegthumbnailer is not currently supported in cmakelists.txt , but I see some defines in the code.

Is it not supported (yet) or broken?

On the side note: huge thanks for trying to revive mediatomb, I loved that project in the good old days.

**Comment by v00d00** [comment]
That is a good point, I hadn't noticed that omission as I personally never used that feature.

I will look into getting a flag added.

**Comment by asavah** [comment]
Thanks
